# Generated by Django 4.2.20 on 2025-05-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='social_media_links',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='portfolio.socialmedialink'),
        ),
    ]
